---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: otariinae-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/aurora-dx-nvidia-open
image-version: stable-daily # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: os-release
    properties:
      ID: AuroraOtarinae
      NAME: Aurora-Otarrinae
      PRETTY_NAME: WinnieOS

  - type: dnf
    repos:
      cleanup: true
      files: 
        - https://repository.mullvad.net/rpm/stable/mullvad.repo
        - https://repo.secureblue.dev/secureblue.repo
      copr:
        - ublue-os/staging
        - ublue-os/packages
        - swayfx/swayfx
        - derenderkeks/proxmox-backup-client
    optfix:
      - Mullad VPN
    install:
      install-weak-deps: false
      packages:
        - mullvad-vpn
        - trivalent
#        - perl-File-Copy
#        - fontconfig.i686
#        - fontconfig.x86_64
#        - gstreamer1-plugins-bad-free.i686
#        - gstreamer1-plugins-bad-free.x86_64
#        - gstreamer1-plugins-base.i686
#        - gstreamer1-plugins-base.x86_64
#        - gstreamer1-plugins-good.i686
#        - gstreamer1-plugins-good.x86_64
#        - gstreamer1.i686
#        - gstreamer1.x86_64
#        - libXcomposite.i686
#3        - libXcomposite.x86_64
#        - libXinerama.i686
#        - libXinerama.x86_64
#        - nss-mdns.i686
#        - nss-mdns.x86_64
#        - pcsc-lite-libs.i686
#        - pcsc-lite-libs.x86_64
#        - pulseaudio-libs.i686
#        - pulseaudio-libs.x86_64
#        - sane-backends-libs.i686
#        - sane-backends-libs.x86_64
#        - vulkan-loader.i686
#        - vulkan-loader.x86_64
        - swayfx
        - fuzzel
        - i3blocks
        - proxmox-backup-client
        - gparted
        - swaylock
        - swayidle
        - slurp
        - sway-systemd
        - xdg-desktop-portal-wlr
        - grim
        - nvidia-container-toolkit
  - type: script
    scripts:
      - selinux.sh
#      - sway.sh


  - type: signing # this sets up the proper policy & signing files for signed images to work fully


  - type: dnf
    repos:
      cleanup: true
      files: 
        - https://repository.mullvad.net/rpm/stable/mullvad.repo
        - https://repo.secureblue.dev/secureblue.repo
      copr:
        - ublue-os/staging
        - ublue-os/packages
        - swayfx/swayfx
