---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: otariinae-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/blue-build/base-images/fedora-base-nvidia
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: containerfile
    snippets:
      - COPY --from=ghcr.io/ublue-os/brew:latest /system_files /
  - type: copy
    from: ghcr.io/projectbluefin/common:latest
    src: /system_files/shared
    dest: /
  - type: dnf
    repos:
      cleanup: true
      files: 
        - https://repository.mullvad.net/rpm/stable/mullvad.repo
        - https://repo.secureblue.dev/secureblue.repo
        - https://download.docker.com/linux/fedora/docker-ce.repo
        - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
      copr:
        - ublue-os/staging
        - ublue-os/flatpak-test
        - ublue-os/packages
        - swayfx/swayfx
        - derenderkeks/proxmox-backup-client
        - secureblue/run0edit
        - secureblue/trivalent
        - amyiscoolz/komnenos
    install:
      install-weak-deps: false
      packages:
        - mullvad-vpn
        - uupd
        - ublue-os-udev-rules
        - trivalent
        - trivalent-subresource-filter
        - run0edit
        - osbuild-selinux
        - docker-ce
        - tailscale
        - containerd.io
        - docker-buildx-plugin
        - docker-ce-cli
        - docker-compose-plugin
        - docker-model-plugin
#        - perl-File-Copy
#        - fontconfig.i686
#        - fontconfig.x86_64
#        - gstreamer1-plugins-bad-free.i686
#        - gstreamer1-plugins-bad-free.x86_64
#        - gstreamer1-plugins-base.i686
#        - gstreamer1-plugins-base.x86_64
#        - gstreamer1-plugins-good.i686
#        - gstreamer1-plugins-good.x86_64
#        - gstreamer1.i686
#        - gstreamer1.x86_64
#        - libXcomposite.i686
#3        - libXcomposite.x86_64
#        - libXinerama.i686
#        - libXinerama.x86_64
#        - nss-mdns.i686
#        - nss-mdns.x86_64
#        - pcsc-lite-libs.i686
#        - pcsc-lite-libs.x86_64
#        - pulseaudio-libs.i686
#        - pulseaudio-libs.x86_64
#        - sane-backends-libs.i686
#        - sane-backends-libs.x86_64
#        - vulkan-loader.i686
#        - vulkan-loader.x86_64
        - swayfx
        - fuzzel
        - i3blocks
        - proxmox-backup-client
        - gparted
        - swaylock
        - swayidle
        - slurp
        - sway-systemd
        - xdg-desktop-portal-wlr
        - grim
        # - nvidia-container-toolkit
        # DEV
        - cmake
        - ninja-build
        - gtk3-devel
        - libstdc++-static
        - mesa-libGLU
        - clang
        # - pkg-config
        # - mesa-libGLU-devel
        # EXTRA SHIT
        - wireshark
        - kernel-headers
    replace:
      - from-repo: copr:copr.fedorainfracloud.org:ublue-os:flatpak-test
        packages:
          - flatpak
          - flatpak-libs
          - flatpak-session-helper
      - from-repo: copr:copr.fedorainfracloud.org:amyiscoolz:komnenos-logos
        packages:
          - old: fedora-logos
            new: komnenos-logos
    group-install:
      with-optional: false
      packages:
        - kde-desktop-environment
    remove:
      packages:
        - appimage-thumbnailer
        - plasma-discover
        - PackageKit
  - type: containerfile
    snippets:
      - RUN dnf5 install -y https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
      - COPY --from=ghcr.io/ublue-os/akmods:main-43 / /tmp/akmods-common
      - RUN find /tmp/akmods-common
      - RUN dnf5 install -y /tmp/akmods-common/rpms/ublue-os/ublue-os-akmods*.rpm --skip-broken
      - RUN dnf5 install -y /tmp/akmods-common/rpms/kmods/kmod-v4l2loopback*.rpm --skip-broken
      - RUN dnf5 install -y /tmp/akmods-common/rpms/kmods/kmod-xone*.rpm --skip-broken
      - RUN dnf5 install -y /tmp/akmods-common/rpms/kmods/kmod-framework-laptop*.rpm --skip-broken
      - RUN dnf5 install -y /tmp/akmods-common/rpms/kmods/kmod-openrazer*.rpm --skip-broken
  - type: script
    scripts:
      - selinux.sh
#      - sway.sh
      - droidcam.sh
  - type: systemd
    # this example disables automatic flatpak updates and enables a custom service unit for all users
    system:
      enabled:
        - docker.socket
        - sddm.service
        - flatpak.preinstall.service
        - rechunker-group-fix.service
        - tailscaled.service
        - brew-upgrade.timer
        - brew-setup.service
        - uupd.timer
        - brew-update.timer
    user:
      enabled:
        - my-custom.service
      disabled:
        - flatpak-user-update.timer
  - type: os-release
    properties:
      ID: Otarinae
      NAME: Otarrinae
      PRETTY_NAME: WinnieOS

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
